name: reviewdog

on: [pull_request]

jobs:
  golangci-lint:
    name: runner / golangci-lint
    strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint with review dog
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--config=.golangci.yml"
          level: error
          reporter: github-pr-review
          go_version: ${{ matrix.go-version }}
          fail_on_error: true
