name: lint

on:
  pull_request:

jobs:
  lint-with-reviewdog:
    name: lint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          golangci_lint_flags: "--config=.golangci.yml"
          level: error
          filter_mode: nofilter
          reporter: github-pr-review
          go_version: "1.17"
          fail_on_error: true
