name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: go test
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20']
    runs-on: ubuntu-22.04

    steps:
      - name: check out code into the Go module directory
        uses: actions/checkout@v3

      - name: set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: restore cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: get dependencies
        run: |
          go mod download

      - name: test
        run: go test -race ./...

