name: test_lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    strategy:
      matrix:
        go-version: [1.15, 1.16, 1.17]
    runs-on: ubuntu-latest

    steps:
      - name: check out code into the Go module directory
        uses: actions/checkout@v2

      - name: set up Go 1.1x
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: get dependencies
        run: |
          go mod download

      - name: test
        run: go test ./... -v

  lint-with-reviewdog:
    name: lint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: nofilter
          reporter: github-pr-review
